### ISSUE TITLE
Remove /ids/ out of REST API path

### ISSUE THREAD

**Issue by yzhao244** [openmessaging/openschema#13]
I would like to suggest to remove /ids/ from the following GET RESTful Urls because /ids/ is usually hidden from a RESTful url. :)
GET /schemas/ids/{string: id}/subjects
GET /schemas/ids/{string: id}

The following urls are my suggested changes. 
GET /schemas/{string: id}/subjects
GET /schemas/{string: id}

**Comment by vongosling** [comment]
@duhenglucky thoughts?
