### ISSUE TITLE
English Version of OpenSchema Specification

### ISSUE THREAD

**Issue by yzhao244** [openmessaging/openschema#4]
I am a user of openschema and I'm extremely interested in contributing to this project. I have gone through the project related to  OpenSchema specification and would like to contribute to the community with an English Version of OpenSchema [specification](https://github.com/openmessaging/openschema/blob/master/spec.md)
I will prepare and get back to the community for further discussions through this issue.

**Comment by vongosling** [comment]
@yzhao244 any progress for here :-)

**Comment by yzhao244** [comment]
@vongosling Working in progress. I should have a first english version to contribute and review soon.
