### ISSUE TITLE
Representation consistency and Compatibility check

### ISSUE THREAD

**Issue by JunjieChou** [openmessaging/openschema#6]
some representations are not consistent, I think there lacks compatibility check errcode in several interfaces, and some alter may be applied to subtitles or examples

**Comment by vongosling** [comment]
Thanks for your options, I would like to invite you to check the latest spec two weeks later. @duhenglucky

**Comment by JunjieChou** [comment]
> Thanks for your options, I would like to invite you to check the latest spec two weeks later. @duhenglucky

Thanks, It's a great pleasure.

I have currently started coding the server side of a Open Schema Registry based on spring-boot.

Will there be any updates recently(more likely this week)? 
If yes, I will wait for the newly version. If not, I will code following the original spec and update codes in the future.
